from dotenv import load_dotenv
import os
import disnake
from disnake.ext import commands
import datetime
import requests
import random
import csv
from collections import defaultdict 

load_dotenv()
DISCORD_TOKEN = os.getenv("DISCORD_TOKEN")

def get_all_champions():
    url = "http://ddragon.leagueoflegends.com/cdn/13.19.1/data/en_US/champion.json"
    champions_data = requests.get(url).json()["data"]
    return [champion["name"] for champion in champions_data.values()]

def get_halloween_skins_from_csv(filename):
    skins = defaultdict(list)
    with open(filename, "r") as file:
        reader = csv.reader(file)
        for champion, skin, _, _ in reader:
            skins[champion].append(skin)
    return skins

def select_unique_champions(champions, count):
    selected = random.sample(champions, count)
    for champ in selected:
        champions.remove(champ)
    return selected

def generate_random_teams_with_skins(all_champions, halloween_skins):
    team1, team2 = [], []

    halloween_champions = list(halloween_skins.keys())
    team1.extend(select_unique_champions(halloween_champions, 3))
    team2.extend(select_unique_champions(halloween_champions, 3))
    
    available_champions = [champ for champ in all_champions if champ not in team1 and champ not in team2]
    team1.extend(select_unique_champions(available_champions, 12))
    team2.extend(select_unique_champions(available_champions, 12))
    
    return team1, team2

bot = commands.InteractionBot()

all_champions_list = get_all_champions()
halloween_skins = get_halloween_skins_from_csv("final_skin_list.csv")

def create_team_embed(team1, team2):
    def sorted_team_formatting(team):
        halloween_champions = list(halloween_skins.keys())
        # Splitting into two lists
        with_skins = [champ for champ in team if champ in halloween_champions]
        without_skins = list(set(team) - set(with_skins))

        # Sorting each list
        with_skins.sort()
        without_skins.sort()

        # Merging the lists
        return with_skins, without_skins

    # Sort and format each team
    team1_skins, team1 = sorted_team_formatting(team1)
    team2_skins, team2 = sorted_team_formatting(team2)

    embed = disnake.Embed(
        color=disnake.Colour.blue(),
        timestamp=datetime.datetime.now(),
    )
    embed.set_thumbnail(url="http://raw.communitydragon.org/pbe/plugins/rcp-be-lol-game-data/global/default/v1/champion-splashes/9/9004.jpg")

    embed.set_author(
        name="Spooky ARAM Team Generator",
        icon_url="https://ddragon.leagueoflegends.com/cdn/13.10.1/img/champion/Fiddlesticks.png",  # Example logo
    )
    embed.set_footer(
        text="Generated by CeSU Bot",
    )

    # Adding Red Team as a field
    embed.add_field(name=f"Blue Team - Spooky Points (max {len(team1_skins)})", value="\n".join([f"{champ} - {', '.join(halloween_skins[champ])}" for champ in team1_skins]), inline=False)
    embed.add_field(name="Blue Team", value="\n".join([champ for champ in team1]), inline=False)
    embed.add_field(name=f"Red Team - Spooky Points (max {len(team2_skins)})", value="\n".join([f"{champ} - {', '.join(halloween_skins[champ])}" for champ in team2_skins]), inline=False)
    embed.add_field(name="Red Team", value="\n".join([champ for champ in team2]), inline=False)

    return embed

@bot.slash_command()
async def halloween_aram(ctx):
    team1, team2 = generate_random_teams_with_skins(all_champions_list, halloween_skins)
    embed = create_team_embed(team1, team2)
    await ctx.send(embed=embed)

bot.run(DISCORD_TOKEN)